apiVersion: v1
kind: Pod
metadata:
  name: beverages
spec:
  containers:
  - name: pepsi
    image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - mountPath: "/volume"
        name: shared-volume
  - name: coke
    image: "registry.access.redhat.com/ubi8/ubi-minimal:latest"
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - mountPath: "/volume"
        name: shared-volume
  volumes:
    - name: shared-volume
      emptyDir: {}
  restartPolicy: Never
